### ISSUE TITLE
Přesun menu na JQuery 2.2.1

### ISSUE THREAD

**Issue by kikinna** [KB009/network-visualization#25]

**Comment by KB009** [comment]
Je přechod nutný/vhodný? Obě by měly být totožné, až na podporu prohlížeče IE. Viz informace z oficiální stránky:

> jQuery 2.x has the same API as jQuery 1.x, but does not support Internet Explorer 6, 7, or 8.

**Comment by kikinna** [comment]
Víteker si to vyžádal (je to hned první odrážka v poznámkách, které posílal.
